### DISCUSSION TITLE
Some basic controls

### DISCUSSION THREAD

**Discussion by xHirscHx** [HASwitchPlate/openHASP#127] [General]
For the life of me i could not get 2 switches to work on same page  until i changed the 1 to a 2 in the second switch and now they work. Do i do this for every switch on the plate or just page and what is it. 
P.S. rookie  here.
```
      - obj: "p3b4" # switch, checkbox or btn with toggle true
        properties:
          "val": "{{ 1 if states('light.my_lamp') == 'on' else 0 }}"
        event:
          "on":
            service: light.turn_on
            target:
              entity_id: "light.my_lamp"
          "off":
            service: light.turn_off
            target:
              entity_id: "light.my_lamp"

      - obj: "p3b5" # switch, checkbox or btn with toggle true
        properties:
          "val": "{{ 2 if states('light.my_test') == 'on' else 0 }}"    
        event:
          "on":
            service: light.turn_on
            target:
              entity_id: "light.my_test"
          "off":
            service: light.turn_off
            target:
              entity_id: "light.my_test"
```
