### DISCUSSION TITLE
Home Assistant custom component event control

### DISCUSSION THREAD

**Discussion by m3730r** [HASwitchPlate/openHASP#159] [Q&A] [answered]
How can I control different scenes with the event options?

        event:
          "up":
            - service: scene.turn_on
              target:
                entity_id: >-
                  {% if val == 0 %}
                    scene.light_night
                  {%-elif val == 1 %}
                    scene.light_day
                  {% endif %}

throws configuration error 

Invalid config for [openhasp]: not a valid value for dictionary value @ data['openhasp']['plate_sz']['objects'][0]['event']['up'][0]['target']['entity_id']. Got '{% if val == 0 %}\n scene.light_night\n{%-elif val == 1 %}\n scene.light_day\n{% endif %}'. (See /home/h0bi/.homeassistant/configuration.yaml, line 186). 

Are there other options, e.g. on off events?

**Comment by dgomes** [comment]
From the error message I take it the problem is on the service configuration. I suggest you first experiment the syntax on the developer tools page of Home Assistant

**Reply by m3730r** [reply]
I‘ve tried different versions syntax, but no success:

          "up":
            - service: scene.turn_on
              entity_id: >
               {% if val == 0 %}
                 scene.light_night
               {% else %}
                 scene.light_day
               {% endif %}
 
This works in the template editor in HA, but not in the configuration.yaml.
 It is the same syntax like the examples in the documentation. But no success.

this weird writing seems to work, because there is no configuration error, but it turns both scenes on

 ```
         "up":
            - service: scene.turn_on
              entity_id: 
#               {% if val == 0 %}
                 - scene.light_night
#               {% else %}
                 - scene.light_day
#               {% endif %}
```

Any suggestions?
