### DISCUSSION TITLE
AM312 Motion Sensor

### DISCUSSION THREAD

**Discussion by DSRocker** [HASwitchPlate/openHASP#272] [Hardware]
I tried the AM312 Motion Sensor on different GPIOs. Configured / selected the GPIO as an Input-Pin in HASP. But nothing happens.
The Plate is integrated in Home Assistant; but the Sensor is not discoverd...
Do I have to pay attention to anything else?

**Comment by nagyrobi** [comment]
You need to write some custom C code to make it work that way, dude.

**Reply by DSRocker** [reply]
Oh ok. The same woth other devices like relay, LEDs,...?
Do you have an example for me how to do it?

**Reply by nagyrobi** [reply]
Not yet, this is wotk in progress

**Comment by DSRocker** [comment]
I would like to compile my own version, but it does not work with VSC. The compiling is sucsessful but the ESP blinking after flashing the bin and nothing happens...

**Reply by fvanroie** [reply]
What ESP32 and TFT are you using? And which environment did you compile the firmware for?
The hardware and firmware configurations need to match or it won't run properly...

**Reply by DSRocker** [reply]
ESP32 WROOM 32
I compiled D1mini for the esp32. Is it wrong?
And what about motion sensor ? Is it possible to use it?
Thanks a lot!!!

**Reply by fvanroie** [reply]
> I compiled D1mini for the esp32. Is it wrong?

It depends on what ESP32 dev-board and TFT are you using... the compiled firmware configuration *must* match the hardware pins.

>  And what about motion sensor ? Is it possible to use it?

I think it should work by just connecting it to an input pin. Check the Pull-Up / Pull-Down resistor configuration.
Check in the openHASP or MQTT logs if movement is detected.

**Reply by DSRocker** [reply]
I use this board with the pin configuration like wirtten:
https://haswitchplate.github.io/openHASP-docs/latest/displays/MSPxxxx/

Which pin do you recommend to use for the motion sensor on the esp32 wroom?

**Reply by DSRocker** [reply]
motion sensor works fine on GPIO27. Thanks!

**Comment by htvekov** [comment]
Hi'
I use an AM312 sensor with one of my wt32-sc01 plates to turn on backlight if presence is detected. Works perfectly !
I'm using pin 4, inverted and type presence.

![image](https://user-images.githubusercontent.com/45469813/152605033-63a63190-aad8-4d8f-a88d-027e46afb445.png)

Small `"page":0,"id":8` plate config to indicate PIR (little green/red man) on the display in my top bar:

![image](https://user-images.githubusercontent.com/45469813/152605256-b74bcb00-13f7-463f-9360-877549581811.png)

```jsonl
{"page":0,"obj":"roller","id":4,"enabled":false,"x":0,"y":0,"w":320,"h":45,"val":0,"rows":1,"options":"PAGE 1\nSONOS\nOFFICE\nPAGE 4\nPAGE 5","text_font":24,"bg_opa":100,"bg_color1":"#000000","text_color1":"#FFFFFF","bg_color":"#000000","text_color":"#000000","border_side":0,"radius":0}
{"page":0,"obj":"label","id":5,"enabled":false,"x":227,"y":5,"h":45,"w":90,"text":"\ue50f 00.0°C","align":2,"bg_color":"#2C3E50","text_color":"#FFFFFF","text_font":24}
{"page":0,"page":0,"id":6,"obj":"label","enabled":false,"x":3,"y":5,"h":45,"w":62,"text":"00:00","align":0,"bg_color":"#2C3E50","text_color":"#FFFFFF","text_font":24}
{"page":0,"id":7,"obj":"label","enabled":false,"x":60,"y":2,"w":30,"h":45,"text":"\uE5A9","bg_color":"#2C3E50","text_color":"#FFFFFF","text_font":16}
{"page":0,"id":8,"obj":"label","enabled":false,"x":75,"y":2,"w":30,"h":45,"text":"\ue004","bg_color":"#2C3E50","text_color":"green","text_font":16}
```

And two small automations to change glyph/colour on precense detection as well as wake up plate (turn off idle mode)
This could easily be done as custom component config as well.

```yaml
- id: hasp_pir_on_display_wt32_02_mqtt
  alias: hasp_pir_on_display_wt32_02_mqtt
  mode: single
  trigger:
    platform: mqtt
    topic: hasp/wt32_02/state/input4
    payload: '{"state":"on"}'
  action:
  - service: mqtt.publish
    data:
      topic: hasp/wt32_02/command/idle
      payload: 'off'
  - service: mqtt.publish
    data:
      topic: hasp/wt32_02/command
      payload: 'jsonl {"page":0,"id":8,"text_color":"maroon","text":"\ue64a"}'
      
- id: hasp_pir_off_display_wt32_02_mqtt
  alias: hasp_pir_off_display_wt32_02_mqtt
  mode: single
  trigger:
    platform: mqtt
    topic: hasp/wt32_02/state/input4
    payload: '{"state":"off"}'
  action:
  - service: mqtt.publish
    data:
      topic: hasp/wt32_02/command
      payload: 'jsonl {"page":0,"id":8,"text_color":"green","text":"\ue004"}' 
```

That's it, I guess. Give it a shot ! 😉🙋‍♂️

**Reply by jazzmonger** [reply]
Success!  I also noticed a new binary sensor was automatically added to HOME ASSISTANT.  As I battled getting MQTT working (finally got it) I used this to trigger it from pin 35. 
```
trigger:
  - platform: state
    entity_id:
      - binary_sensor.plate04_binary_sensor_35
    to: "off"
```
I noticed you have a wifi symbol on id:7 Other than this 
https://openhasp.com/0.7.0/integrations/home-assistant/sampl_conf/#color-coded-icons
I couldnt find  code anywhere for that.  If yours changes signal strength ws/ size and shape, I'd love to see the yaml for that!  Since I'm colorblind, color changes (esp red/greed) on these displays liteerally mean nothing!

**Reply by htvekov** [reply]
> Success! I also noticed a new binary sensor was automatically added to HOME ASSISTANT. As I battled getting MQTT working (finally got it) I used this to trigger it from pin 35.
> 
> ```yaml
> trigger:
>   - platform: state
>     entity_id:
>       - binary_sensor.plate04_binary_sensor_35
>     to: "off"
> ```
> 
> I noticed you have a wifi symbol on id:6. other than this https://openhasp.com/0.7.0/integrations/home-assistant/sampl_conf/#color-coded-icons I couldnt find code anywhere for that. If yours changes signal strength ws/ size and shape, I'd love to see the yaml for that! Since I'm colorblind, color changes (esp red/greed) on these displays liteerally mean nothing!

Using the mqtt topic/payload as a trigger in HA is a bit quicker than triggering on a HA state change. But the job done is completely identical.

I'm afraid I'm only shifting to different colors depending on the rssi signal level. AFAIK there's only one preloaded wifi glyph in openHASP.
This is the object template for color coded RSSI signal level. Not much different than the example:

```yaml
- obj: "p0b7"
        properties:
          "text_color": "{% if -50 <= state_attr('openhasp.sunton_01','rssi') | int(0) %}green{% elif -51 > state_attr('openhasp.sunton_01','rssi') | int(0) >= -60 %}yellow{% elif -61 > state_attr('openhasp.sunton_01','rssi') | int(0) >= -70 %}orange{% elif -71 > state_attr('openhasp.sunton_01','rssi') |int (0) >= -80 %}maroon{% else %}red{% endif %}"
```
