### DISCUSSION TITLE
Esp32 / ILI9341 Display content disappears

### DISCUSSION THREAD

**Discussion by DSRocker** [HASwitchPlate/openHASP#287] [General]
Hi,
I use the esp32 wroom with the red pcb touch display ili9341 and it worked fine. But now the content disappears after few seconds after booting. The backlight is on and the touch function works.
Here a short video :
https://youtu.be/KpROZu5gLwA

Thanks!

**Comment by nagyrobi** [comment]
There's an issue happening after it connects to the network. Try removing your plate from HA, does it still hsppen?

**Reply by DSRocker** [reply]
I disabled the openHASP integration in HA and now it works; but without HA integration it's useless...
I updated the HASP OTA (https://github.com/HASwitchPlate/openHASP/releases/download/v0.6.2/d1-mini-esp32_ili9341_full_4MB_v0.6.2.bin)
The version is now 0.7; don't know why. The for HA is integration is 0.6....

What could be the solution for this issue integration?
Thx

**Reply by nagyrobi** [reply]
Good, it's likely something in your config yaml in HA that makes it blow.

I suggest to start with an empty config from scratch, add blocks back one by one and restart HA after each. To find which part of the config is the culprit.

**Reply by DSRocker** [reply]
I think I've found the issue. Now HA doesn't discover the plate.
openHASP is installed (HACS) and is available in "integrations". MQTT is connected. 
When I try to add the integration I get the error:
"Aborted
Configuration is done through discovery"

I rebooted HA, Plate, ... nothink...

**Reply by nagyrobi** [reply]
reboot the plate multiple times. it will be re-discovered after a while.

**Reply by DSRocker** [reply]
Version 0.6.x discoverd
Version 0.7.x is not recognized / discovered

**Reply by nagyrobi** [reply]
One step at a time. You should stick to 0.6 first and try debugging you config issues with that.

**Comment by fvanroie** [comment]
Please post the `openhasp` config in your `configuration.yaml` and the openHASP logs when the content disappears happens.

**Reply by DSRocker** [reply]
where to find the logs?

**Reply by fvanroie** [reply]
In the `telnet` or `serial` console you will find the debug output.

**Comment by DSRocker** [comment]
HA configuration.yaml:
```yaml
openhasp: !include ds_openhasp.yaml # Touch-Display
```
ds_openhasp.yaml:
```yaml
  hasp_touch_1:           # plateXYZ: Your plate identifier slug. For each plate in your sytem,
#----------------------clock----------------
    objects:
      - obj: "p0b1"
        properties:
          "text": "{{ states('sensor.time') }}"
          
#----------------------Temperature----------------
      - obj: "p0b2"
        properties:
          "text": "{{ states('sensor.cpu_temperature') }}°C"
          
#----------------------Buttons - Lights----------------          
      - obj: "p1b1" # Kitchen
        properties:
          "val": '{{ 1 if is_state("switch.dssh4_k", "on") else 0 }}'
          "text": '{{ "\uE6E8" if is_state("switch.dssh4_k", "on") else "\uE335" | e }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: "switch.dssh4_k"
```
