### DISCUSSION TITLE
My Hasp displays "Connecting..." continuously and not connecting with Home Assistant.

### DISCUSSION THREAD

**Discussion by rarenu** [HASwitchPlate/openHASP#326] [Q&A] [answered]
Hi I am 74 retired Telecom Engineer and my hobby is IoT. My openHASP sends and receives fine with my other MQTT broker and the nodes. 
But when I try to integrate with Home Assistant, it always displays "Connecting...". Home Assistant's HACS shows openHASP but not linking with it. May be the Home Assistant is not recognizing it. 
```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

openhasp:
  plate35:
    objects:
      - obj: "p0b1" # temperature label on all pages
        properties:
          "text": '{{ states("sensor.my_room_temperature") }}°C'
      - obj: "p1b2" # light-switch toggle button
        properties:
          "val": '{{ 1 if states("light.my_room") == "on" else 0 }}'
          "text": '{{ "\uE6E8" if is_state("light.my_room", "on") else "\uE335" | e }}'
        event:
          "up":
            - service: homeassistant.toggle
              entity_id: "light.my_room"
      - obj: "p1b3" # dropdown
        event:
          "changed":
            - service: persistent_notification.create
              data:
                message: I like {{ text }}
```
The " /config/custom_components" folder shows 2 folders 1. "HACS", 2. "open Hasp" . The open Hasp folder has list of related files.

Please help me. Thank and best wishes.

**Comment by fvanroie** [comment]
Try adding this (temporarily) to your `configuration.yaml` to enable logging:
```
logger:
  default: warning
  logs:
    custom_components.openhasp: debug
```
Reboot HA to enable it and then check the logs for errors or clues what might be happening when the plate connects.
