### DISCUSSION TITLE
Converting weather card to NWS - National Weather Service

### DISCUSSION THREAD

**Discussion by jazzmonger** [HASwitchPlate/openHASP#433] [General]
Im hoping someone else has cracked this nut.  I have a weather plate and used the example to great effect.  But here in the USA, the National Weather Service integration has, what I've found anyway, to be the most accurate, esp when you get outside major cities.  The local temps and forecast are often spot on. As a plus, it has an hourly sensor and a forecast sensor, all in one integration.

https://www.home-assistant.io/integrations/nws/

HOWEVER, when replacing the existing weather service Met.no & OpenWeatherMap (https://www.home-assistant.io/integrations/openweathermap/) (which has terrible forecast and current info here in the USA), with the NWS integration the attributes are slightly different and in different places, rendering what could be a nice card, unusable.

for example, while it is cloudy and 38F the rest of it makes no sense.
![image](https://user-images.githubusercontent.com/52110065/220507884-44569efe-9cdb-48fb-bd91-2d866a867256.png)

and this screen is all wrong, 
![image](https://user-images.githubusercontent.com/52110065/220507907-2216ad65-866a-49c5-a52b-ea723da72cba.png)

It should be consecutive days with high and low temps.  I know the data is there, but what the gifted code jockey who wrote this is doing in the OpenHASPs yaml to derrive the dates and data from the entity is _**FAR**_ above my pay grade.  There's no way I can decipher it at that level.

So has anyone else cracked this one?  I'd love to use this plate with good data here in the US.

Here's a dump from the forecast sensor, and the hourly sensor is noted and pasted a ways down.
```
temperature: 33
temperature_unit: °F
humidity: 56
pressure: 29.44
pressure_unit: inHg
wind_bearing: 270
wind_speed: 9.17
wind_speed_unit: mph
visibility: 10
visibility_unit: mi
precipitation_unit: in
forecast: 
- detailed_description: >-
    Isolated snow showers before 11pm. Mostly cloudy, with a low around 27. West
    northwest wind 9 to 14 mph, with gusts as high as 24 mph. Chance of
    precipitation is 20%.
  datetime: '2023-02-21T19:00:00-07:00'
  daytime: false
  condition: snowy
  precipitation_probability: 20
  wind_bearing: 292.5
  temperature: 27
  wind_speed: 11.5
- detailed_description: >-
    A slight chance of snow showers after 11am. Partly sunny, with a high near
    40. West northwest wind 10 to 15 mph. Chance of precipitation is 20%.
  datetime: '2023-02-22T06:00:00-07:00'
  daytime: true
  condition: snowy
  precipitation_probability: 20
  wind_bearing: 292.5
  temperature: 40
  wind_speed: 12.5
- detailed_description: >-
    A slight chance of snow showers. Mostly cloudy, with a low around 24.
    Southwest wind 8 to 20 mph. Chance of precipitation is 20%.
  datetime: '2023-02-22T18:00:00-07:00'
  daytime: false
  condition: snowy
  precipitation_probability: 20
  wind_bearing: 225
  temperature: 24
  wind_speed: 14
- detailed_description: >-
    A chance of snow showers before 5pm. Mostly cloudy, with a high near 38.
    South southeast wind 14 to 22 mph. Chance of precipitation is 30%.
  datetime: '2023-02-23T06:00:00-07:00'
  daytime: true
  condition: snowy
  precipitation_probability: 30
  wind_bearing: 157.5
  temperature: 38
  wind_speed: 18
- detailed_description: Mostly cloudy, with a low around 22. Southeast wind 6 to 15 mph.
  datetime: '2023-02-23T18:00:00-07:00'
  daytime: false
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 22
  wind_speed: 10.5
- detailed_description: Mostly sunny, with a high near 43.
  datetime: '2023-02-24T06:00:00-07:00'
  daytime: true
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 43
  wind_speed: 9
- detailed_description: Mostly clear, with a low around 22.
  datetime: '2023-02-24T18:00:00-07:00'
  daytime: false
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 67.5
  temperature: 22
  wind_speed: 7.5
- detailed_description: Sunny, with a high near 45.
  datetime: '2023-02-25T06:00:00-07:00'
  daytime: true
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 67.5
  temperature: 45
  wind_speed: 7
- detailed_description: Mostly clear, with a low around 26.
  datetime: '2023-02-25T18:00:00-07:00'
  daytime: false
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 247.5
  temperature: 26
  wind_speed: 6.5
- detailed_description: >-
    A slight chance of rain showers between 11am and 5pm. Partly sunny, with a
    high near 46. Chance of precipitation is 20%.
  datetime: '2023-02-26T06:00:00-07:00'
  daytime: true
  condition: rainy
  precipitation_probability: 20
  wind_bearing: 225
  temperature: 46
  wind_speed: 8.5
- detailed_description: >-
    A slight chance of snow showers after 5am. Mostly cloudy, with a low around
    28. Chance of precipitation is 20%.
  datetime: '2023-02-26T18:00:00-07:00'
  daytime: false
  condition: snowy
  precipitation_probability: 20
  wind_bearing: 225
  temperature: 28
  wind_speed: 10
- detailed_description: >-
    A slight chance of snow showers before 11am, then a chance of rain showers.
    Mostly cloudy, with a high near 46. Chance of precipitation is 30%.
  datetime: '2023-02-27T06:00:00-07:00'
  daytime: true
  condition: snowy
  precipitation_probability: 30
  wind_bearing: 157.5
  temperature: 46
  wind_speed: 10.5
- detailed_description: >-
    A chance of rain showers before 11pm, then a chance of snow showers. Mostly
    cloudy, with a low around 32. Chance of precipitation is 30%.
  datetime: '2023-02-27T18:00:00-07:00'
  daytime: false
  condition: snowy
  precipitation_probability: 30
  wind_bearing: 180
  temperature: 32
  wind_speed: 13
- detailed_description: >-
    A slight chance of snow showers before 11am, then a slight chance of rain
    showers. Partly sunny, with a high near 47. Chance of precipitation is 20%.
  datetime: '2023-02-28T06:00:00-07:00'
  daytime: true
  condition: snowy
  precipitation_probability: 20
  wind_bearing: 180
  temperature: 47
  wind_speed: 11

attribution: Data from National Weather Service/NOAA
friendly_name: KEUL Daynight
```
And a dump from the hourly sensor
```
temperature: 33
temperature_unit: °F
humidity: 56
pressure: 29.44
pressure_unit: inHg
wind_bearing: 270
wind_speed: 9.17
wind_speed_unit: mph
visibility: 10
visibility_unit: mi
precipitation_unit: in
forecast: 
- detailed_description: ''
  datetime: '2023-02-21T19:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 36
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-21T20:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 292.5
  temperature: 34
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-21T21:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 292.5
  temperature: 33
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-21T22:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 292.5
  temperature: 32
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-21T23:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 31
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T00:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 31
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T01:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 30
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T02:00:00-07:00'
  condition: cloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 30
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T03:00:00-07:00'
  condition: cloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 29
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T04:00:00-07:00'
  condition: cloudy
  precipitation_probability: 7
  wind_bearing: 292.5
  temperature: 29
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T05:00:00-07:00'
  condition: cloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 28
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T06:00:00-07:00'
  condition: cloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 28
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T07:00:00-07:00'
  condition: cloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 28
  wind_speed: 13
- detailed_description: ''
  datetime: '2023-02-22T08:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 28
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T09:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 30
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T10:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 4
  wind_bearing: 292.5
  temperature: 33
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T11:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 35
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-22T12:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 36
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-22T13:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 38
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-22T14:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 38
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T15:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 39
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T16:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 315
  temperature: 39
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-22T17:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 292.5
  temperature: 39
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T18:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 292.5
  temperature: 36
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T19:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 292.5
  temperature: 34
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-22T20:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 270
  temperature: 31
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-22T21:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 270
  temperature: 30
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-22T22:00:00-07:00'
  condition: snowy
  precipitation_probability: 21
  wind_bearing: 270
  temperature: 30
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-22T23:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 180
  temperature: 28
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-23T00:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 180
  temperature: 28
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-23T01:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 180
  temperature: 27
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-23T02:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 135
  temperature: 27
  wind_speed: 16
- detailed_description: ''
  datetime: '2023-02-23T03:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 135
  temperature: 27
  wind_speed: 16
- detailed_description: ''
  datetime: '2023-02-23T04:00:00-07:00'
  condition: snowy
  precipitation_probability: 15
  wind_bearing: 135
  temperature: 26
  wind_speed: 16
- detailed_description: ''
  datetime: '2023-02-23T05:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 26
  wind_speed: 20
- detailed_description: ''
  datetime: '2023-02-23T06:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 25
  wind_speed: 20
- detailed_description: ''
  datetime: '2023-02-23T07:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 25
  wind_speed: 20
- detailed_description: ''
  datetime: '2023-02-23T08:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 25
  wind_speed: 18
- detailed_description: ''
  datetime: '2023-02-23T09:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 26
  wind_speed: 18
- detailed_description: ''
  datetime: '2023-02-23T10:00:00-07:00'
  condition: snowy
  precipitation_probability: 19
  wind_bearing: 135
  temperature: 28
  wind_speed: 18
- detailed_description: ''
  datetime: '2023-02-23T11:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 135
  temperature: 30
  wind_speed: 22
- detailed_description: ''
  datetime: '2023-02-23T12:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 135
  temperature: 32
  wind_speed: 22
- detailed_description: ''
  datetime: '2023-02-23T13:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 135
  temperature: 34
  wind_speed: 22
- detailed_description: ''
  datetime: '2023-02-23T14:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 157.5
  temperature: 35
  wind_speed: 17
- detailed_description: ''
  datetime: '2023-02-23T15:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 157.5
  temperature: 36
  wind_speed: 17
- detailed_description: ''
  datetime: '2023-02-23T16:00:00-07:00'
  condition: snowy
  precipitation_probability: 31
  wind_bearing: 157.5
  temperature: 36
  wind_speed: 17
- detailed_description: ''
  datetime: '2023-02-23T17:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 157.5
  temperature: 35
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-23T18:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 157.5
  temperature: 34
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-23T19:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 157.5
  temperature: 32
  wind_speed: 14
- detailed_description: ''
  datetime: '2023-02-23T20:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 135
  temperature: 30
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-23T21:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 135
  temperature: 28
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-23T22:00:00-07:00'
  condition: cloudy
  precipitation_probability: 6
  wind_bearing: 135
  temperature: 28
  wind_speed: 15
- detailed_description: ''
  datetime: '2023-02-23T23:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 27
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T00:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 27
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T01:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 26
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T02:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 26
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-24T03:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 25
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-24T04:00:00-07:00'
  condition: cloudy
  precipitation_probability: 2
  wind_bearing: 135
  temperature: 24
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-24T05:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 24
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T06:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 23
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T07:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 22
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T08:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 23
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T09:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 25
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T10:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 29
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-24T11:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 32
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T12:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 35
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T13:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 135
  temperature: 38
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T14:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 40
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T15:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 42
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T16:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 43
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-24T17:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 42
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T18:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 40
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T19:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 112.5
  temperature: 36
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-24T20:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 0
  temperature: 32
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-24T21:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 0
  temperature: 30
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-24T22:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 0
  temperature: 29
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-24T23:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 180
  temperature: 28
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T00:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 180
  temperature: 28
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T01:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 180
  temperature: 27
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T02:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 90
  temperature: 27
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T03:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 90
  temperature: 26
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T04:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 90
  temperature: 25
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T05:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 0
  temperature: 25
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T06:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 0
  temperature: 24
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T07:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 0
  temperature: 24
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T08:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 45
  temperature: 24
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T09:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 45
  temperature: 27
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T10:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 1
  wind_bearing: 45
  temperature: 31
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-25T11:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 35
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-25T12:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 38
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-25T13:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 40
  wind_speed: 7
- detailed_description: ''
  datetime: '2023-02-25T14:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 42
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-25T15:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 44
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-25T16:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 90
  temperature: 45
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-25T17:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 67.5
  temperature: 44
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-25T18:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 67.5
  temperature: 42
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-25T19:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 67.5
  temperature: 38
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-25T20:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 0
  temperature: 35
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T21:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 0
  temperature: 33
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T22:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 2
  wind_bearing: 0
  temperature: 32
  wind_speed: 6
- detailed_description: ''
  datetime: '2023-02-25T23:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 270
  temperature: 31
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T00:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 270
  temperature: 31
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T01:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 270
  temperature: 30
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T02:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 202.5
  temperature: 29
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T03:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 202.5
  temperature: 29
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T04:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 6
  wind_bearing: 202.5
  temperature: 28
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T05:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 202.5
  temperature: 28
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T06:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 202.5
  temperature: 27
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T07:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 202.5
  temperature: 27
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T08:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 28
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T09:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 30
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T10:00:00-07:00'
  condition: partlycloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 33
  wind_speed: 5
- detailed_description: ''
  datetime: '2023-02-26T11:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 180
  temperature: 36
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-26T12:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 180
  temperature: 40
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-26T13:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 180
  temperature: 42
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-26T14:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 270
  temperature: 44
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T15:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 270
  temperature: 45
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T16:00:00-07:00'
  condition: rainy
  precipitation_probability: 17
  wind_bearing: 270
  temperature: 45
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T17:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 45
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T18:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 43
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T19:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 41
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-26T20:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 39
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-26T21:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 38
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-26T22:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 270
  temperature: 37
  wind_speed: 10
- detailed_description: ''
  datetime: '2023-02-26T23:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 247.5
  temperature: 36
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-27T00:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 247.5
  temperature: 35
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-27T01:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 247.5
  temperature: 34
  wind_speed: 9
- detailed_description: ''
  datetime: '2023-02-27T02:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 33
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T03:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 33
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T04:00:00-07:00'
  condition: cloudy
  precipitation_probability: 14
  wind_bearing: 180
  temperature: 32
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T05:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 31
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T06:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 30
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T07:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 30
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T08:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 31
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T09:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 33
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T10:00:00-07:00'
  condition: snowy
  precipitation_probability: 16
  wind_bearing: 157.5
  temperature: 36
  wind_speed: 8
- detailed_description: ''
  datetime: '2023-02-27T11:00:00-07:00'
  condition: rainy
  precipitation_probability: 22
  wind_bearing: 157.5
  temperature: 40
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-27T12:00:00-07:00'
  condition: rainy
  precipitation_probability: 22
  wind_bearing: 157.5
  temperature: 42
  wind_speed: 12
- detailed_description: ''
  datetime: '2023-02-27T13:00:00-07:00'
  condition: rainy
  precipitation_probability: 22
  wind_bearing: 157.5
  temperature: 44
  wind_speed: 12

```
