### DISCUSSION TITLE
Weather font icon corresponding by name instead code

### DISCUSSION THREAD

**Discussion by exotsk** [HASwitchPlate/openHASP#463] [Q&A] [answered]
Can I call the icon by name? for example (weather-cloudy), in order not to write ifelse for many lines for the connection of weather conditions in the forecast home assistant and the code of the corresponding icon in the embedded font openhasp.
this would be much easier than downloading icons as png and summoning from as an example. I would be satisfied with standard built-in icons.
to make such a visualization as in the photo, I will need to describe 5 times all the weather conditions for the icon of each day. this is a lot of copypaste code lines.
![image](https://user-images.githubusercontent.com/54969124/230721285-f7a05325-107f-46cb-a8f3-57eec35a8543.png)

**Comment by fvanroie** [comment, marked as answer]
@schafran figured out this mega elegant solution to convert HA weather condition to icon codes:

```yaml
- obj: "p1b21"
    properties:
      "text": >-
        {% set icons = {"cloudy":"\uE590", "fog":"\uE591", "hail":"\uE592", "lightning":"\uE593", "clear-night":"\uE594", "partlycloudy":"\uE595", "pouring":"\uE596", "rainy":"\uE597", "snowy":"\uE598", "sunny":"\uE599", "windy":"\uE59D", "windy-variant":"\uE59E", "lightning-rainy":"\uE67E", "snowy-rainy":"\uE67F", "exceptional":"\uE957"} %}
        {{ icons[states("weather.your_entity")] | default("\uE957") }}
```

**Reply by schafran** [reply]
Also I guess the new macros in templating introduced in 2023.4 could help reduce code duplication (say if we need stuff in 5 different locations)... Haven't checked it out yet though

**Comment by exotsk** [comment]
Thanks! it`s look good for me =)
![image](https://user-images.githubusercontent.com/54969124/230728358-d04b19f1-164a-47d1-b6dd-ae1c15f8d565.png)
If anyone need
element:
```
{"page":1,"id":200,"obj":"bar","x":120,"y":315,"h":25,"w":158,"min":0,"max":100,"val":0,"start_value":0}
{"page":1,"id":201,"obj":"label","x":282,"y":315,"w":33,"h":25,"toggle":true,"text":"000","text_font":21,"mode":"break","align":1}
{"page":1,"id":202,"obj":"label","x":83,"y":315,"w":33,"h":25,"toggle":true,"text":"000","text_font":21,"mode":"break","align":1}
{"page":1,"id":203,"obj":"label","x":52,"y":315,"w":33,"h":25,"toggle":true,"text":"","text_font":21,"mode":"break","align":1}
{"page":1,"id":204,"obj":"label","x":4,"y":315,"w":50,"h":25,"toggle":true,"text":"00.00","text_font":21,"mode":"break","align":1}
```

in ha side:

```
plate36:
  objects:
    - obj: "p1b200"  # Tomorrow
      properties:
        "val":  "{{state_attr('weather.forecast_home_assistant', 'forecast')[0].temperature}}"
        "start_value":  "{{state_attr('weather.forecast_home_assistant', 'forecast')[0].templow}}"
        "min": "{{state_attr('weather.forecast_home_assistant','forecast') | map(attribute='templow') | min}}"
        "max": "{{state_attr('weather.forecast_home_assistant','forecast') | map(attribute='temperature') | max}}"
    - obj: "p1b201"  # Tomorrow
      properties:
        "text": "{{state_attr('weather.forecast_home_assistant', 'forecast')[0].temperature}}"
    - obj: "p1b202"  # Tomorrow
      properties:
        "text": "{{state_attr('weather.forecast_home_assistant', 'forecast')[0].templow}}"
    - obj: "p1b204"  # Tomorrow
      properties:
        "text": "{{as_timestamp(state_attr('weather.forecast_home_assistant', 'forecast')[0].datetime) | timestamp_custom('%d.%m') }}"
    - obj: "p1b203" 
      properties:
        "text": >-
            {% set icons = {"cloudy":"\uE590", "fog":"\uE591", "hail":"\uE592", "lightning":"\uE593", "clear-night":"\uE594", "partlycloudy":"\uE595", "pouring":"\uE596", "rainy":"\uE597", "snowy":"\uE598", "sunny":"\uE599", "windy":"\uE59D", "windy-variant":"\uE59E", "lightning-rainy":"\uE67E", "snowy-rainy":"\uE67F", "exceptional":"\uE957"} %}
            {{icons[state_attr('weather.forecast_home_assistant','forecast')[0]['condition']] | default("\uE957")}}
```
