### DISCUSSION TITLE
How do I set the permanent backlight to say 1% on idle?

### DISCUSSION THREAD

**Discussion by Rumbaar** [HASwitchPlate/openHASP#478] [General]
I'd prefer to have the 'switch' always on, so at least can see that it's a switch and has functions.  I can see short and long idle settings, but how do I define what happens at those 'long idle' stages?  I'd like to set it to 100% for active, short idle can stay as is, but have long idle or until set, have it stay 'on' at 1%.

Is that possible or a work around to achieve this?

**Comment by stovedoctor** [comment]
If using home assistant the setting in on the device info page

**Reply by stovedoctor** [reply]
![Screenshot_20230502-211555.png](https://user-images.githubusercontent.com/60519485/235831995-9ad02285-f2ed-488c-93ee-732e93fd216c.png)

![Screenshot_20230502-211651.png](https://user-images.githubusercontent.com/60519485/235832032-79b54ec8-b504-4126-9e28-789391ea6c16.png)

**Reply by Rumbaar** [reply]
> If using home assistant the setting in on the device info page

That is currently set to '35' out of 255 and the until, as a whole, turns the backlight off after the 'long idle' time set in configuration.  If that is meant to keep the display on, then it's not working as intended and doesn't stop the backlight turning off.

So for your setup, if you set that, it'll sit at the DIM setting until pressed and then go back to full brightness?

**Reply by htvekov** [reply]
Well, The openHASP custom component fully controls backlight state and brightness level for the three device states (`idle_off`, `idle_short` &` idle_long`).
You can configure some of these elements, but not all in the custom component.
When openHASP device issues an `idle_long`  MQTT message, the custom component replies with a `{"state": 0, "brightness": XX}` command.

Best approach to avoid any change from `idle_short` to `idle_long` would be to 'hack' custom components `light.py` file.
As alternative you could hardcode brightness level for `idle_long` events to whatever value you want
Below a simple, crude hack. You could also just eliminate all `idle_long` replies from the CC

We need a more 'sofisticated' solution in the CC for numerous reasons. Alternatively this should be handled locally in the openHASP code. I ran into same issue implementing custom code for a proximity sensor
https://github.com/HASwitchPlate/openHASP-custom-component/issues/103

```python
async def async_listen_idleness(self):
        """Listen to messages on MQTT for HASP idleness."""

        @callback
        async def idle_message_received(msg):
            """Process MQTT message from plate."""
            message = HASP_IDLE_SCHEMA(msg.payload)

            if message == HASP_IDLE_OFF:
                brightness = self._awake_brightness
                backlight = 1
            elif message == HASP_IDLE_SHORT:
                brightness = self._idle_brightness
                backlight = 1
            elif message == HASP_IDLE_LONG:
                # brightness = self._awake_brightness
                brightness = self._idle_brightness
                # backlight = 0
                backlight = 1
```

**Reply by stovedoctor** [reply]
I'm sorry I thought it did.
I have no use for it because I use the automation to load a dark object when screen is off to protext my device from burn in.
```
alias: open hasp black object overlay
description: |-
  Renders black overlay when backlight is off to prevent burn in.
  Deletes when back light on.
trigger:
  - platform: device
    type: turned_off
    device_id: 23afc290179d4e3298cf60c1dd840683
    entity_id: light.desk_backlight
    domain: light
    id: backlight off
  - platform: device
    type: turned_on
    device_id: 23afc290179d4e3298cf60c1dd840683
    entity_id: light.desk_backlight
    domain: light
    id: backlight on
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: backlight off
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/jsonl
              payload: >-
                {"page":0,"id":99,"obj":"obj","x":0,"y":0,"w":320,"h":480,"radius":0,"hidden":0,"bg_grad_dir":0,"bg_color":"black"}
      - conditions:
          - condition: trigger
            id: backlight on
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/p0b99.hidden
              payload: "1"
          - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/p0b99.delete
              payload: ""
mode: single
```
