### DISCUSSION TITLE
Alexa Timers - finally able to use in OpenHasp

### DISCUSSION THREAD

**Discussion by jazzmonger** [HASwitchPlate/openHASP#497] [General]
I FINALLY got some help and am able to pull Alexa timers out of the convoluted Alexa attributes.... what a major pain...
I updated the wiki for others battling this:
https://github.com/custom-components/alexa_media_player/wiki#alexa-timers

you end up with this:
<img width="1103" alt="image" src="https://github.com/HASwitchPlate/openHASP/assets/52110065/074cb90e-6257-429b-9840-865acfd93dab">

So finally we have sensors that can now be displayed as countdown timers in OpenHasp.  Now I'd like to have the Kitchen Sunton display switch to a new page with the timers for 5 seconds WHILE any timer is active and then switch back to whatever screen was previously displayed until no timer is active then stay on the original screen.

Not sure how to accomplish that yet...

**Comment by jazzmonger** [comment]
Heres a first pass! I want to add cancel buttons to each timer but that is proving tedious. 
When any timers become active, the screen switches to the Alexa Timers screen

![image](https://github.com/HASwitchPlate/openHASP/assets/52110065/b754d7e7-a366-42cf-85f3-1fb9ea33ab50)

configuration.yaml:
```
template:
  - sensor:
    - name: "Alexa Timer 1"
      icon: mdi:timer-outline
      state: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[0] in sorted_active %}
              {{ (sorted_active[0][1].triggerTime|int /1000 -  (as_timestamp(now()))) | timestamp_custom('%H:%M:%S', false)}}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}   
      attributes:
        label: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[0] in sorted_active %}
              {{ sorted_active[0][1].timerLabel }}
            {% else %}Timer 1{% endif %}
          {% else %}Timer 1{% endif %}
          
    - name: "Alexa Timer 2"
      icon: mdi:timer-outline
      state: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[1] in sorted_active %}
              {{ (sorted_active[1][1].triggerTime|int /1000 -  (as_timestamp(now()))) | timestamp_custom('%H:%M:%S', false)}}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}   
      attributes:
        label: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[1] in sorted_active %}
              {{ sorted_active[1][1].timerLabel }}
            {% else %}Timer 2{% endif %}
          {% else %}Timer 2{% endif %}          

    - name: "Alexa Timer 3"
      icon: mdi:timer-outline
      state: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[2] in sorted_active %}
              {{ (sorted_active[2][1].triggerTime|int /1000 -  (as_timestamp(now()))) | timestamp_custom('%H:%M:%S', false)}}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}   
      attributes:
        label: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[2] in sorted_active %}
              {{ sorted_active[2][1].timerLabel }}
            {% else %}Timer 3{% endif %}
          {% else %}Timer 3{% endif %}  
```
screen jason:
```
{"id":1,"obj":"label","x":100,"y":100,"w":450,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Alexa Timer1","text_color":"white","text_font":56}
{"id":2,"obj":"label","x":100,"y":200,"w":450,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Alexa Timer2","text_color":"white","text_font":56}
{"id":3,"obj":"label","x":100,"y":300,"w":450,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Alexa Timer3","text_color":"white","text_font":56}

{"id":9,"obj":"label","x":440,"y":100,"w":210,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Timer1","text_color":"white","text_font":56}
{"id":10,"obj":"label","x":440,"y":200,"w":210,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Timer2","text_color":"white","text_font":56}
{"id":11,"obj":"label","x":440,"y":300,"w":210,"h":90,"border_color":"#848a94","border_width":0,"radius":5,"bg_color":"#5a6173","text":"Timer3","text_color":"white","text_font":56}
```

and Plate YAML code:
```
#Alexa Timers
    - obj: "p5b9"  # timer 1
      properties:
        "text": >
          {% if states('sensor.alexa_timer_1') is not none %}
            {{ states('sensor.alexa_timer_1') }}
          {%- endif %}
          "opacity": "{{ 60 if (is_state('sensor.alexa_timer_1','unavailable') or is_state('sensor.alexa_timer_1','unknown')) else 255 }}"
    - obj: "p5b1"  # timer 1 name
      properties:
        "text": >
          {% if state_attr('sensor.alexa_timer_1','label') is not none %}
          {{ state_attr('sensor.alexa_timer_1','label') }}
          {% else -%}
          No Name
          {%- endif %}
    - obj: "p5b10"  # timer 2
      properties:
        "text": >
          {% if states('sensor.alexa_timer_2') is not none %}
            {{ states('sensor.alexa_timer_2') }}
          {%- endif %}
          "opacity": "{{ 60 if (is_state('sensor.alexa_timer_2','unavailable') or is_state('sensor.alexa_timer_2','unknown')) else 255 }}"
    - obj: "p5b2"  # timer 2 name
      properties:
        "text": >
          {% if state_attr('sensor.alexa_timer_2','label') is not none %}
          {{ state_attr('sensor.alexa_timer_2','label') }}
          {% else -%}
          No Name
          {%- endif %}     
    - obj: "p5b11"  # timer 3
      properties:
        "text": >
          {% if states('sensor.alexa_timer_3') is not none %}
            {{ states('sensor.alexa_timer_3') }}
          {%- endif %}
          "opacity": "{{ 60 if (is_state('sensor.alexa_timer_3','unavailable') or is_state('sensor.alexa_timer_3','unknown')) else 255 }}"
    - obj: "p5b3"  # timer 3 name
      properties:
        "text": >
          {% if state_attr('sensor.alexa_timer_3','label') is not none %}
          {{ state_attr('sensor.alexa_timer_3','label') }}
          {% else -%}
          No Name          
          {%- endif %}
    - obj: "p5b12"  # cancel ALL timers  
      properties:      
       "click": "{{ 'false' if states('media_player.kitchen_original') in ['unavailable', 'unknown'] else 'true' }}"
       "text": >
          {% if states('sensor.alexa_timer_1') is not none %}
            Cancel ALL Timers
          {% else -%}
            Alexa Timers   
          {%- endif %}  
      event:
        "down":
          - service: media_player.play_media
            target:
              entity_id: media_player.kitchen_original
            data:
              media_content_type: custom
              media_content_id: 'cancel all timers' 
```
And an automation to change to the timers page if one becomes active:
```
alias: HASP Alexa Timers
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.alexa_timer_1
    attribute: label
    from: unavailable
  - platform: state
    entity_id:
      - sensor.alexa_timer_2
    attribute: label
    from: unavailable
  - platform: state
    entity_id:
      - sensor.alexa_timer_3
    attribute: label
    from: unavailable
  - platform: state
    entity_id:
      - sensor.alexa_timer_1
    to: unavailable
condition: []
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.hasp_kitchen_saved_page
      value: "{{ states('number.plate02_page_number') }}"
    alias: Save the page we are currently on
  - service: mqtt.publish
    data:
      topic: hasp/plate02/command
      payload_template: page {{ 5 }}
      qos: "0"
    alias: "MQTT: change to page 5, Alexa Timers"
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: false
  - service: mqtt.publish
    data:
      topic: hasp/plate02/command
      payload_template: page {{ states('input_number.hasp_kitchen_saved_page') |int(0) }}
      qos: "0"
    alias: "MQTT: Change to saved page"
    enabled: false
  - if:
      - condition: state
        entity_id: sensor.alexa_timer_1
        state: unavailable
    then:
      - service: mqtt.publish
        data:
          topic: hasp/plate02/command
          payload_template: page {{ states('input_number.hasp_kitchen_saved_page') |int(0) }}
          qos: "0"
        alias: "MQTT: Change to saved page after Alexa timers expire"
        enabled: true
mode: single
```
