### DISCUSSION TITLE
Media player progress bar

### DISCUSSION THREAD

**Discussion by Sonusss** [HASwitchPlate/openHASP#524] [Q&A]
Hi,

I used the example to make a media player control.
It works great except for the media progress bar which is updated only on action like play, pause, next item, etc...
Is this behavior normal ?

**Comment by htvekov** [comment]
Yep. HA only updates the media player attributes (e.g. `media_position`) upon state changes (play, paused, stopped, idle)
So, when playing,  you'll need to calculate time spend from `media_position_updated_at` to current time and update the objects yourselves.

You can check out my Sonos automation below that does exactly that:

```
# Every five seconds - Push media_duration to plates when playing
# Don't push update for Sonos sources (radio stations) - check for media_position attribute presence
# When paused, page will get exact update from HA's media player state changes and update plates
## 0303023 Revised media_duration to cope with Spotify Radio
- id: openhasp_update_media_duration
  alias: openHASP update media duration
  mode: single
  trigger:
    platform: time_pattern
    seconds: '/5'
  condition:
    condition: template
    value_template: "{{ (true if state_attr(state_attr('group.sonos_all','entity_id')[0], 'media_position') != None else false) and states('sensor.hasp_sonos_master_state') == 'playing' }}"
  action:
    service: mqtt.publish
    data_template:
      topic: hasp/plates/command/p2b41.val
      payload: >-
          {{ (as_timestamp(now(),0) - as_timestamp(state_attr(state_attr('group.sonos_all', 'entity_id')[0], 'media_position_updated_at'),0)) | round(0) + (state_attr(state_attr('group.sonos_all', 'entity_id')[0], 'media_position')) | int(0) }}
```
