### DISCUSSION TITLE
Using HA to update Message box popups with input text Manually or with automation.

### DISCUSSION THREAD

**Discussion by stovedoctor** [HASwitchPlate/openHASP#554] [Show and tell]
Thought I would share on how I use popup message boxes.
by manually displaying a message via HA dash board using a input text box.
![textbox](https://github.com/HASwitchPlate/openHASP/assets/60519485/1910951c-e738-4410-82f7-9bc7f2eebd18)

![popup](https://github.com/HASwitchPlate/openHASP/assets/60519485/1ee31adb-eef5-484a-93b6-bb67748c2479)

or using event triggers to display a pop up message. such as if a door is open for a set amount of time.
![slideropen](https://github.com/HASwitchPlate/openHASP/assets/60519485/40794938-fea5-40aa-a8e6-872bef4499e9)
I also have one if my Power usages is more than my solar production. 
![Screenshot 2023-10-02 162255](https://github.com/HASwitchPlate/openHASP/assets/60519485/59cc9ebf-349b-455f-9a49-9385b6f4de71)

Thanks to @fvanroie for the help with how to clear a popup when events are done. 
``` - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/p0b70.delete
```
This all works great for me to get Barbara's attention by having pop ups on the panel connected between to her two computer monitors. (hard to get her attention when she is in Team meetings)
![image](https://github.com/HASwitchPlate/openHASP/assets/60519485/146d9283-9b68-4967-822e-3c250ff36139)
Automaton for having a HA text box in a HA dashboard create a message box.  by adding `{{ states("input_text.ha_panel_popup_text_box") }}` where you normal put your message text.
this automation also clears the message box when the input text box is cleared.
```
alias: Openhasp POPup text box
description: >-
  display popup on all openhasp panels the text box data. Clear popup if text
  box is Empty or cleared.
trigger:
  - platform: state
    entity_id:
      - input_text.ha_panel_popup_text_box
    id: text
    enabled: true
condition: []
action:
  - service: mqtt.publish
    data:
      qos: 0
      topic: hasp/plates/command/jsonl
      payload: >-
        {"page":0,"id":75,"obj":"msgbox","bg_color":"white","text_color":"Red","text":"
        {{ states("input_text.ha_panel_popup_text_box") }}
        ","options":["Close"]}
  - type: turn_on
    device_id: 23afc290179d4e3298cf60c1dd840683
    entity_id: light.desk_backlight
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 88b53314416b4ce885e73c349b11de1b
    entity_id: light.desk1_backlight
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: ff2aa76f6ac729f1e9e243fa22ce23e1
    entity_id: light.plate35_backlight
    domain: light
    brightness_pct: 100
  - condition: state
    entity_id: input_text.ha_panel_popup_text_box
    state: ""
  - service: mqtt.publish
    data:
      topic: hasp/plates/command/p0b75.delete
mode: single
```
Using a event trigger such as if a sliding door is left open for a few minutes (damn cat!)
This automation will show a pop up if the door is left open for 2 minutes and clear it after the door is closed.
YOU NEED THE ABOVE automation first for this to work........
```
alias: slider open popup
description: display popup on openhasp if slider is left open.
trigger:
  - platform: state
    entity_id:
      - binary_sensor.door_2
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 2
      seconds: 0
condition: []
action:
  - service: input_text.set_value
    data:
      value: Slider door has been open for over TWO minutes
    target:
      entity_id: input_text.ha_panel_popup_text_box
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_2
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 2
    timeout:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
    continue_on_timeout: true
  - service: input_text.set_value
    data:
      value: ""
    target:
      entity_id: input_text.ha_panel_popup_text_box
  - service: mqtt.publish
    data:
      topic: hasp/plates/command/p0b75.delete
mode: single
```
HIGH power usage more than our solar production during the day.
```
alias: openhasp low solar production
description: "using more power than producing POP up. clear when less power used. "
trigger:
  - platform: state
    entity_id:
      - binary_sensor.using_pge
    id: low production
    for:
      hours: 0
      minutes: 0
      seconds: 5
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.using_pge
    id: OK production
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: "off"
condition:
  - condition: time
    weekday:
      - thu
      - wed
      - tue
      - mon
      - sun
      - fri
      - sat
    after: "10:00:00"
    before: "17:00:00"
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - low production
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/jsonl
              payload: >-
                {"page":0,"id":70,"obj":"msgbox","bg_color":"white","text_color":"Red","text":"\uE026
                USING PGE!  \uF40B Solar production LOW","options":["Close"]}
          - type: turn_on
            device_id: 23afc290179d4e3298cf60c1dd840683
            entity_id: light.desk_backlight
            domain: light
            brightness_pct: 100
          - type: turn_on
            device_id: 88b53314416b4ce885e73c349b11de1b
            entity_id: light.desk1_backlight
            domain: light
            brightness_pct: 100
          - type: turn_on
            device_id: ff2aa76f6ac729f1e9e243fa22ce23e1
            entity_id: light.plate35_backlight
            domain: light
            brightness_pct: 100
      - conditions:
          - condition: trigger
            id:
              - OK production
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              topic: hasp/plates/command/p0b70.delete
mode: single
```
I have one set in my laundry notification automation also
![Screenshot 2023-10-02 164521](https://github.com/HASwitchPlate/openHASP/assets/60519485/54cd79dd-0068-4e10-acd9-216e80104abb)
