### DISCUSSION TITLE
Popup window with toggling button

### DISCUSSION THREAD

**Discussion by elik745i** [HASwitchPlate/openHASP#575] [General]
He guys, yesterday I added popup to confirm critical switches on my device: however the problem is - I can't get around toggle enabled btn elemet to display correct state. When I hit button, popup comesup but button changes state to ON even if I hit reject button on popup.
Any ideas are highly appreciated.

My code on the device pages.jsol:

`{"page":2,"id":6,"obj":"btn","x":10,"y":190,"w":140,"h":40,"toggle":true,"text":"OLD GATE","text_font":18,"mode":"break","align":1}`

Instructions sent on toggle from HA:

```
     - obj: "p2b6" # gate01 control
        properties:
          "val": '{{ 1 if states("switch.gate01_control") == "on" else 0 }}'
          "text": '{{ "GATE01 ON" if is_state("switch.gate01_control", "on") else "GATE01 OFF" | e }}'
        event:
          "up":
            - service: openhasp.command      # display the on-demand pop-up with extra setting objects, tagged with the entity_id and specific positions in JSON objects
              target:
                entity_id: openhasp.remote02
              data:
                keyword: jsonl
                parameters: >-
                  {"page":2,"id":200,"obj":"obj","x":0,"y":0,"w":240,"h":320,"radius":0,"bg_grad_dir":0,"opacity":150,"bg_color":"black"}
                  {"page":2,"id":210,"obj":"obj","parentid":200,"x":0,"y":40,"w":240,"h":240,"opacity":255,"click":0,"radius":10,"shadow_opa":255,"shadow_color":"black","shadow_width":20,"shadow_spread":0}
                  {"page":2,"id":211,"obj":"label","parentid":210,"x":10,"y":10,"w":210,"h":40,"click":0,"align":"center","text_font":32,"text":"GATE01 CONTROL!"}
                  {"page":2,"id":201,"obj":"btn","parentid":210,"x":130,"y":90,"w":100,"h":90,"toggle":true,"text":"YES","text_font":32,"mode":"break","align":1}
                  {"page":2,"id":212,"obj":"btn","parentid":210,"x":10,"y":90,"w":100,"h":90,"toggle":true,"text":"NO","text_font":32,"mode":"break","align":1}
                  
      - obj: "p2b201"  
        event:
          "up":
            - service: homeassistant.toggle
              entity_id: "switch.gate01_control"
            - service: openhasp.command
              target:
                entity_id: openhasp.remote02
              data:
                keyword: p2b200.delete


      - obj: "p2b212" # the background of the popup. when touched directly, will close the popup by deleting its objects
        event:
          "down":
            - service: openhasp.command
              target:
                entity_id: openhasp.remote02
              data:
                keyword: p2b200.delete
```
