### DISCUSSION TITLE
Is there a way to show time in 12 hour format?

### DISCUSSION THREAD

**Discussion by Grey-Lancaster** [HASwitchPlate/openHASP#621] [General]
yaml
```
      - obj: "p0b6"
        properties:
          "text": "{{ states('sensor.time') }}"            
#          "text": "{{ states("{{ now().strftime('%I:%M %p') }}" }}"  
```

![image](https://github.com/HASwitchPlate/openHASP/assets/20055899/fa70fc8c-3250-4247-8ea8-61864c9b801f)

**Comment by xHirscHx** [comment]
put this in your yaml. file under sensors and use timepm not  time.
```yaml
  - platform: template
    sensors:
      timepm:
        friendly_name: 'timepm'
        value_template: >
          {% set time = states('sensor.time') %}
          {% set hour = time[:2]|int %}
          {{ '{:02d}:{} {}'.format(hour if hour == 12 else hour % 12, time[3:5], 'PM' if hour>11 else 'AM') }}
```
