### DISCUSSION TITLE
Using value of a different object in Home Assistant config

### DISCUSSION THREAD

**Discussion by jofotoo** [HASwitchPlate/openHASP#654] [Q&A]
I can see you can use templates like  {{ text }} or {{ val }} for events of that object, but I'm looking to use something another object. Is there a way to reference another object's value in the HA config?   I think it would look like this, but it's not working...

```
      - obj: "p3b25" 
        event:
          "down":
            - service: persistent_notification.create
              data:
                message: Selected {{ p3b5.val }}
```
Is this even possible? I couldn't find any examples in the docs

TIA
