### DISCUSSION TITLE
Button function on tab's not working

### DISCUSSION THREAD

**Discussion by Suschibomber** [HASwitchPlate/openHASP#720] [Q&A]
I have been trying for 2 days to make a button usable on your tab page, which simply takes me to a specific page.
Unfortunately, nothing happens when I click on the button. Is it perhaps not even possible to use a button on a tab?

![image](https://github.com/HASwitchPlate/openHASP/assets/51985160/650e91c0-c515-4277-b2f7-a0d9186f95ad)

esp32s3display.json

```
    [
        "SEITE 1 - SETTINGS",
            {
                "page": 1,
                "id": 1,
                "obj": "img",
                "src": "L:/hk-House-sw.png",
                "auto_size": 0,
                "w": 480
            },
            "SEITE 0 - PREVIOUS -BUTTON",
            {
                "page": 0,
                "id": 1,
                "obj": "btn",
                "bg_opa": 80,
                "outline_opa": 0,
                "border_opa": 0,
                "text_font": 32,
                "toggle": false,
                "action": "prev"
            },
            "SEITE 0 - HOME - BUTTON",
            {
                "page": 0,
                "id": 2,
                "obj": "btn",
                "bg_opa": 80,
                "outline_opa": 0,
                "border_opa": 0,
                "text_font": 32,
                "toggle": false,
                "action": {
                    "down": "page 1",
                    "hold": "page 12"
                }
            },
            "SEITE 0 - NEXT - BUTTON",
            {
                "page": 0,
                "id": 3,
                "obj": "btn",
                "bg_opa": 80,
                "outline_opa": 0,
                "border_opa": 0,
                "text_font": 32,
                "toggle": false,
                "action": "next"
            },
            "SEITE 0 - DATUM + UHRZEIT",
            {
                "page": 0,
                "id": 4,
                "obj": "label",
                "align": "center",
                "text_color": "#FFF",
                "text_font": 18
            },
            "SEITE 0 - TEMP - ICON",
            {
                "page": 0,
                "id": 9,
                "obj": "btn",
                "bg_opa": 0,
                "border_width": 0,
                "text_font": 22,
                "text":"\uEAD7"
            },            
            "SEITE 0 - Wifi - ICON",
            {
                "page": 0,
                "id": 10,
                "obj": "label",
                "bg_opa": 0,
                "border_width": 0,
                "text_font": 18,
                "text":"\uE5A9"
            },
            "SEITE 1 - WETTER - CONTAINER",
            {
                "page": 1,
                "id": 2,
                "obj": "obj",
                "border_opa": 0,
                "bg_opa": 0,
                "click": 0
            },
            "SEITE 1 - WETTER - IMAGE",
            {
                "page": 1,
                "id": 14,
                "parentid": 2,
                "obj": "img",
                "src": "L:/openhasp_dummy_img.png",
                "auto_size": 1,
                "pad_top": 10,
                "pad_bottom": 10,
                "pad_left": 10,
                "pad_right": 10,
                "tollge": "false",
                "action": "p5"
            },
            "SEITE 1 - TEMPERATUR - LABEL",
            {
                "page": 1,
                "id": 16,
                "parentid": 2,
                "obj": "label",
                "text": "--°C",
                "text_font": 32
            },
            "SEITE 1 - CONDITION - LABEL",
            {
                "page": 1,
                "id": 17,
                "parentid": 2,
                "obj": "label",
                "text": "condition"
            },
            "SEITE 1 - DOTS - LABEL",
            {
                "page": 1,
                "id": 19,
                "parentid": 2,
                "obj": "label",
                "text": "#ffffff \u2022# #909090 \u2022#",
                "text_font": 24,
                "text_color": "grey"
            },
            "SEITE 1 - CONTAINER - TABVIEW",
            {
                "page": 1,
                "id": 10,
                "parentid": 2,
                "obj": "tabview",
                "btn_pos": 0,
                "bg_opa": 0,
                "border_width": 0,
                "text_font": 24
            },
            "SEITE 1 - TAB1 - TAB",
            {
                "page": 1,
                "id": 11,
                "parentid": 10,
                "obj": "tab"
            },
            "SEITE 1 - TAB2 - TAB",
            {
                "page": 1,
                "id": 12,
                "parentid": 10,
                "obj": "tab"
            },
            "SEITE 1 - TAB1 - TEMPERATUR",
            {
                "page": 1,
                "id": 21,
                "obj": "obj",
                "parentid": 11,
                "x": 23,
                "y": 155,
                "w": 98,
                "h": 98,
                "radius": 50,
                "bg_color": "#FFF",
                "border_color": "#FFF",
                "bg_opa": 0,
                "value_str": "23\u00b0C",
                "value_color": "#FFF",
                "click": 0
            },
            "SEITE 1 - TAB1 - TEMPERATUR-LABEL",
            {
                "page": 1,
                "id": 22,
                "obj": "label",
                "parentid": 11,
                "x": 23,
                "y": 260,
                "h": 98,
                "w": 98,
                "text": "Temperatur",
                "text_color": "#FFF",
                "text_font": 18,
                "align": "center",
                "click": 0
            },
            "SEITE 1 - LUFTFEUCHTIGKEIT",
            {
                "page": 1,
                "id": 23,
                "obj": "obj",
                "parentid": 11,
                "x": 135,
                "y": 155,
                "w": 98,
                "h": 98,
                "radius": 50,
                "bg_color": "#FFF",
                "border_color": "#FFF",
                "bg_opa": 0,
                "value_str": "35%",
                "value_color": "#FFF",
                "click": 0
            },
            "SEITE 1 - TAB1 - LUFTFEUCHTIGKEIT-LABEL",
            {
                "page": 1,
                "id": 24,
                "obj": "label",
                "parentid": 11,
                "x": 135,
                "y": 260,
                "h": 98,
                "w": 98,
                "text": "Feuchtigkeit",
                "text_color": "#FFF",
                "text_font": 18,
                "align": "center",
                "click": 0
            },
            "SEITE 1 - TAB1 - ALLE LICHTER",
            {
                "page": 1,
                "id": 31,
                "obj": "obj",
                "parentid": 11,
                "x": 248,
                "y": 155,
                "w": 98,
                "h": 98,
                "radius": 50,
                "bg_color": "#FFF",
                "border_color": "#FFF",
                "value_str": "\ue335",
                "value_font": 48,
                "value_color": "#0469ad",
                "click": 0
            },
            "SEITE 1 - TAB1 - ALLE LICHTER-LABEL",
            {
                "page": 1,
                "id": 32,
                "obj": "label",
                "parentid": 11,
                "x": 248,
                "y": 260,
                "h": 98,
                "w": 98,
                "text": "2 an",
                "text_color": "#FFF",
                "text_font": 18,
                "align": "center",
                "click": 0
            },
            "SEITE 1 - TAB1 - ALLE ROLLLADEN",
            {
                "page": 1,
                "id": 41,
                "obj": "obj",
                "parentid": 11,
                "x": 360,
                "y": 155,
                "w": 98,
                "h": 98,
                "radius": 50,
                "bg_color": "#FFF",
                "border_color": "#FFF",
                "value_str": "\uF11D",
                "value_font": 48,
                "value_color": "#0469ad",
                "click": 0
            },
            "SEITE 1 - TAB1 - ALLE ROLLLADEN-LABEL",
            {
                "page": 1,
                "id": 42,
                "obj": "label",
                "parentid": 11,
                "x": 360,
                "y": 260,
                "h": 98,
                "w": 98,
                "text": "1 auf",
                "text_color": "#FFF",
                "text_font": 18,
                "align": "center",
                "click": 0
            },
            "SEITE 1 - TAB1 - ROLLLADEN - BUTTON",
            {
                "page": 1,
                "id": 44,
                "obj": "btn",
                "bg_opa": 130,
                "outline_opa": 0,
                "border_opa": 0,
                "text_font": 32,
                "action": "p3",
                "toggle": false,
                "click": 0
            },
            "SEITE 1 - TAB1 - HEIZUNG - BUTTON",
            {
                "page": 1,
                "id": 45,
                "obj": "btn",
                "bg_opa": 130,
                "outline_opa": 0,
                "border_opa": 0,
                "text_font": 32,
                "action": "p4",
                "toggle": false,
                "click": 0
            },
            "SEITE 2 - Test",
            {
                "page": 2,
                "id": 1,
                "obj": "img",
                "src": "L:/hk-Homescreen.png",
                "auto_size": 0,
                "w": 480
            },
            "SEITE 4 - REOLINK - IMAGE - SCHLAFZIMMER",
            {
                "page": 4,
                "id": 1,
                "obj": "img",
                "src": "L:/openhasp.png",
                "auto_size": 1,
                "pad_top": 1,
                "pad_bottom": 1,
                "pad_left": 1,
                "pad_right": 1
            },
            "SEITE 4 - REOLINK - IMAGE - KINDERZIMMER",
            {
                "page": 4,
                "id": 2,
                "obj": "img",
                "src": "L:/openhasp.png",
                "auto_size": 1,
                "pad_top": 1,
                "pad_bottom": 1,
                "pad_left": 1,
                "pad_right": 1
            }                                    
    ]
```

*.yaml:

```
esp32s3wanddisplay1:
  objects:
    # SEITE 0
    #      - obj: "p0b0" # SETTINGS
    #        properties:
    #          "bg_color" : "{% from 'openhasp.jinja' import color %}{{color('bg')}}"
    - obj: "p0b1" # PREVIOUS - BUTTON"
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(4)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(1)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(11)}}"
        "text": "\uE04D"
        "radius": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).radius |int}}"
        "bg_color": "{% from 'openhasp.jinja' import color %}{{color('bg_color')}}"
        "bg_color02": "{% from 'openhasp.jinja' import color %}{{color('primary_light')}}"
    - obj: "p0b2" # HOME - BUTTON
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(4)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(11)}}"
        "text": "\uE6A1"
        "radius": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).radius |int}}"
        "bg_color": "{% from 'openhasp.jinja' import color %}{{color('bg_color')}}"
        "bg_color02": "{% from 'openhasp.jinja' import color %}{{color('primary_light')}}"
    - obj: "p0b3" # NEXT - BUTTON
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(4)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(9)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(11)}}"
        "radius": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).radius |int}}"
        "text": "\uE054"
        "bg_color": "{% from 'openhasp.jinja' import color %}{{color('bg_color')}}"
        "bg_color02": "{% from 'openhasp.jinja' import color %}{{color('primary_light')}}"
    - obj: "p0b4" # DATUM + UHRZEIT LABEL
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(12)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(1)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(1)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(1)}}"
        "text": >-
          {% import 'date_and_time.jinja' as func %}
          {{- func.weekday()|string + ' ' + now().day|string + '.' + func.month()|string + ' - ' + as_timestamp(now())|timestamp_custom("%H:%M") }} Uhr
    - obj: "p0b9" # ICON FARBE THERMOSTAT
      properties:
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(10.3)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(0.8)}}"
        "text_color": "{% if is_state('binary_sensor.xiaomig10', 'on') %}green {% else %}white {% endif %}"
        "text": "{% if is_state('binary_sensor.xiaomig10', 'on') %}\uE438 {% else %}\uEAD7 {% endif %}"
    - obj: "p0b10" # ICON FARBE WIFI SIGNAL
      properties:
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(12)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(1)}}"
        "text_color": "{% if -30 <= state_attr('openhasp.esp32s3wanddisplay1','rssi') |int %}green{% elif -31 > state_attr('openhasp.esp32s3wanddisplay1','rssi') |int >= -50 %}orange{% elif -51 > state_attr('openhasp.esp32s3wanddisplay1','rssi') |int >= -80 %}tomato{% else %}red{% endif %}"

    # SEITE 1: Home
    - obj: "p1b0" # SETTINGS
    #        properties:
    #          "bg_color" : "{% from 'openhasp.jinja' import color %}{{color('bg')}}"
    - obj: "p1b2" # WETTER - CONTAINER
      properties:
        "w": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).display_width}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(10)}}"
        "x": 0
        "y": 0
    - obj: "p1b10" # CONTAINER - TABVIEW
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(12)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(10)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(1)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(1)}}"
      event:
        "changed":
          - service: openhasp.command
            target:
              entity_id: openhasp.esp32s3wanddisplay1
            data:
              keyword: p1b19.text
              parameters: >
                {% if val == 0 %}
                {{ "#ffffff \u2022# #909090 \u2022#" | e }}
                {%-elif val == 1 %}
                {{ "#909090 \u2022# #ffffff \u2022#" | e }}
                {% endif %}
    - obj: "p1b21" # TEMPERATUR
      properties:
        "value_str": '{{ states("sensor.espresense_bt_sensor_a4c138cc9e3e_temperature") | round(0) }}°C'
    - obj: "p1b23" # LUFTFEUCHTIGKEIT
      properties:
        "value_str": '{{ states("sensor.espresense_bt_sensor_a4c138cc9e3e_humidity") | round(0) }}%'
    - obj: "p1b31" # LICHTER (ICON STATUS)
      properties:
        "value_color": "{{ '#ff9e00' if (expand('light.alle_lichter') | selectattr('state','eq','on') | list | count() > 0) else '#FFF' }}"
        "bg_opa": "{{ '255' if (expand('light.alle_lichter') | selectattr('state','eq','on') | list | count() > 0) else '0' }}"
    - obj: "p1b32" # LICHTER (ZÄHLER)
      properties:
        "text": "{{ expand('light.alle_lichter') | selectattr('state','eq','on') | list | count() }} an"
    - obj: "p1b41" # ROLLLADEN (ICON STATUS)
      properties:
        "value_color": "{{ '#4caf50' if (expand('cover.alle_rollladen_ausser_schlafzimmer_tur') | list | count() ) else '#FFF' }}"
        "bg_opa": "{{ '255' if (expand('cover.alle_rollladen_ausser_schlafzimmer_tur') | list | count() > 0) else '0' }}"
    - obj: "p1b42" # ROLLLADEN (ZÄHLER)
      properties:
        "text": "{{ expand('cover.alle_rollladen_ausser_schlafzimmer_tur') | list | count() }} auf"
    - obj: "p1b44" # ROLLLADEN - BUTTON
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(5)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(1.5)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(1.5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(8.6)}}"
        "text": "\uF11C"
        "radius": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).radius |int}}"
        "bg_color": "{% from 'openhasp.jinja' import color %}{{color('bg_color')}}"
        "bg_color02": "{% from 'openhasp.jinja' import color %}{{color('primary_light')}}"
    - obj: "p1b45" # HEIZUNG - BUTTON
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(5)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(1.5)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(7.3)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(8.6)}}"
        "text": "\uE50F"
        "radius": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).radius |int}}"
        "bg_color": "{% from 'openhasp.jinja' import color %}{{color('bg_color')}}"
        "bg_color02": "{% from 'openhasp.jinja' import color %}{{color('primary_light')}}"
    - obj: "p1b14" # WETTER IMAGE
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(2)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(2.8)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(1.7)}}"
        "src": "{{ 'L:/z-128-' + states('weather.forecast_home') + '.png' if not is_state('weather.forecast_home','unavailable') }}"
    - obj: "p1b16" # TEMPERATUR WETTER - LABEL
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(8)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(2.3)}}"
        "text": "{{state_attr('weather.forecast_home', 'temperature')}} °C"
        "align": "center"
    - obj: "p1b17" # CONDITION - LABEL
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(8)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(2)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(3.3)}}"
        "text": "{{ state_translated('weather.forecast_home') }}"
        "align": "center"
    - obj: "p1b19" # DOTS - LABEL
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(4)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(1)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(10)}}"
        "align": "center"
    # SEITE 4
    - obj: "p4b1" # REOLINK - SCHLAFZIMMER
      properties:
        "w": "{% import 'openhasp.jinja' as grid %}{{grid.w(10)}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(10)}}"
        "x": "{% import 'openhasp.jinja' as grid %}{{grid.x(5)}}"
        "y": "{% import 'openhasp.jinja' as grid %}{{grid.y(5)}}"
    - obj: "p4b2" # REOLINK - KINDERZIMMER
      properties:
        "w": "{% from 'openhasp.jinja' import grid %} {{(grid() | from_json).display_width}}"
        "h": "{% import 'openhasp.jinja' as grid %}{{grid.h(10)}}"
        "x": 0
        "y": 0
```

And I also use an additional config for the display settings and the openhasp.jinja for the grid layout.

templates:

```
### OPENHasp ESP32-S3 Displays ###

  - binary_sensor:
    - name: Display Settings
      unique_id: f9e1bf84-fbf0-4111-bd5a-255ebf050fa9 # https://www.uuidgenerator.net/
      state: "{{true}}" # change the default automation entity_id from step 3 before
      delay_on:
        seconds: 2
      attributes:
        update_automation: "automation.update_display_data" # add a the automation entity_id from step 3 before
        update_time: "80" # sending the config via mqtt needs some time to complete. This stops the automation from re.run before sending config is finished
        display_w: "480"
        display_h: "480"
        grid_cols: "12" # increase for more resolution of object
        grid_rows: "12" # increase for more resolution of object
        grid_gutter: "8" # This looked nice for me
        grid_margin: "4" # This looked nice for me
        bg_color: "#000000"
        primary_color: "#4d555c"
        secondary_color: "#ee9f52"
        accent_color: "#A175C4"
        success_color: "#6cbe58"
        warning_color: "#d67430"
        error_color: "#e25628"
        radius: "4"
        media_player: "media_player.raum1" # also change in automation trigger
```
openhasp.jinja:

```
[{%- macro grid() -%}
    {%- set dw = (state_attr('binary_sensor.display_settings', 'display_w') | default(240)) | int -%}
    {%- set dh = (state_attr('binary_sensor.display_settings', 'display_h') | default(240)) | int -%}
    {%- set cols = (state_attr('binary_sensor.display_settings', 'grid_cols') | default(6)) | int -%}
    {%- set rows = (state_attr('binary_sensor.display_settings', 'grid_rows') | default(6)) | int -%}
    {%- set margin = (state_attr('binary_sensor.display_settings', 'grid_margin') | default(10)) | int -%}
    {%- set gutter = (state_attr('binary_sensor.display_settings', 'grid_gutter') | default(10)) | int -%}
    {%- set radius = (state_attr('binary_sensor.display_settings', 'radius') | default(5)) | int -%}
    {{- 
        {
            'w': (dw - (2 * margin) - ((cols-1) * gutter)) / cols, 
            'h': (dh - (2 * margin) - ((rows-1) * gutter)) / rows,
            'cols' : cols,
            'rows' : rows,
            'margin' : margin,
            'gutter' : gutter,
            'display_width' : dw,
            'display_height' : dh,
            'radius': radius
        } | to_json 
    -}}
{%- endmacro -%}

{%- macro w(w) -%}
    {%- set gutter = (grid() | from_json).gutter | default(10) | int -%}
    {%- set errors = namespace(w=[]) %}
    {%- if w > (grid() | from_json).cols or w <= -1 -%}
        {% set errors.w = 'cols must be between 1 and ' + (grid() | from_json).cols | string %}
    {%- endif -%}
    {{- errors.w if errors.w | count > 0 else (w * (grid() | from_json).w | int) + ((w-1) * gutter | int) -}}    
{%- endmacro -%}

{%- macro h(h) -%}
    {%- set gutter = (grid() | from_json).gutter | default(10) | int -%}
    {%- set errors = namespace(h=[]) %}
    {%- if h > (grid() | from_json).rows or h <= -1 -%}
        {% set errors.h = 'rows must be beetween 1 and ' + (grid() | from_json).rows | string %}
    {%- endif -%}
    {{- errors.h if errors.h | count > 0 else (h * (grid() | from_json).h | int) + ((h-1) * gutter | int) -}}    
{%- endmacro -%}

{%- macro x(x) -%}
    {%- set x = x-1 | default(1) -%}
    {%- set margin = (grid() | from_json).margin | default(10) | int -%}
    {%- set gutter = (grid() | from_json).gutter | default(10) | int -%}
    {%- set width = w(x) | int -%}
    {{- (margin if x == 0 else (margin + width + gutter)) if width is number else width -}}
{%- endmacro -%}

{%- macro y(y) -%}
    {%- set y = y-1 | default(1) -%}
    {%- set margin = (grid() | from_json).margin | default(10) | int -%}
    {%- set gutter = (grid() | from_json).gutter | default(10) | int -%}
    {%- set height = h(y) | int -%}
    {{- (margin if y == 0 else (margin + height + gutter)) if height is number else height -}}
{%- endmacro -%}

{%- macro AdjustColor(hex, brightness) -%}
    {%- set brightness = brightness|default(0.1) -%}
    {%- set hex = hex|replace('#', '')|replace('/[^0-9a-f]/gi', '') -%}
    {%- if hex|length < 6 -%}
        {%- set hex = hex[0] + hex[0] + hex[1] + hex[1] + hex[2] + hex[2] -%}
    {%- endif -%}
    {%- set color = namespace(rgb='') -%}
    {%- set color.rgb = '#' -%}
    {%- for i in range(0, 6, 2) -%}
        {%- set c = hex[i:i+2]|int(base=16) -%}
        {%- set c = (c + (c * brightness))|round|int -%} 
        {%- set c = 0 if c < 0 else ( 255 if c > 255 else c) -%}
        {%- set c = "%02x"|format(c) -%}
        {%- set color.rgb = color.rgb + c -%} 
    {%- endfor -%}
    {{- color.rgb -}}
{%- endmacro -%}

{%- macro color(name) -%}
    {%- set s = name.split("_") -%}
    {%- set base = state_attr('binary_sensor.display_settings',  s[0]+'_color') | default('#000000') -%}
    {%- if s | count > 1 and s[1] == 'light' -%}
        {{ AdjustColor(base, 0.2) }}
    {%- elif s | count > 1 and s[1] == 'dark' -%}
        {{ AdjustColor(base, -0.2) }}
    {%-else-%}
        {{ base  -}}
    {%- endif %}
{%- endmacro -%}](url)
```

Thanks for help.
