### DISCUSSION TITLE
Shelly dimmer2 HASP slider to dim

### DISCUSSION THREAD

**Discussion by Emu83** [HASwitchPlate/openHASP#763] [General]
Hi,

I am new to openHASP and still a little green as far as HA goes! I have an SC01 Plus which I have flashed.  I have started a basic design but I am already stuck!  I have a shelly dimmer2 set up in HA via the Shelly integration.  I have added a slider to p1 of my pages.jsonl, I have then added the following code to openhasp.yaml file in HA:

```yaml
obj: "p1b2" # Light brightness
        properties:
          "val": "{{ state_attr('light.shelly_shdm_2_c45bbe78b29f', 'brightness') if state_attr('light.shelly_shdm_2_c45bbe78b29f', 'brightness') != None else 0 }}"
        event:
          "changed":
            - service: light.turn_on
              data:
                entity_id: light.shelly_shdm_2_c45bbe78b29f
                brightness:  "{{ val }}"
          "up":
            - service: light.turn_on
              data:
                entity_id: light.shelly_shdm_2_c45bbe78b29f
                brightness:  "{{ val }}"`
```
Unfortunately it is not working.  Moving the slider does not change the brightness of the lights and changing the brightness of the lights does not reflect on the HASP panel.  Where am I going wrong? Help please!
