### DISCUSSION TITLE
Trying to push an image as a fullscreen background

### DISCUSSION THREAD

**Discussion by mrgrlscz** [HASwitchPlate/openHASP#771] [Q&A] [answered]
Hi there, i'm just trying to push an image as a fullscreen background, but it doesn't fit the whole screen.
Device is elecrow 7" 800x480
Image is obviously 800x480, called `background.png` / 14ko
Looks like this:
![image](https://github.com/user-attachments/assets/43daf94e-b7a5-47df-bc32-a70a76fbbc26)

Here's my pages.jsonl
```
{"comment":"Designer Config","page_size":"7inch_800x480_landscape","plate_name":"elecrow"}
{"page":1,"id":1,"obj":"img","x":0,"y":0,"w":800,"h":480,"src":"","auto_size":1}
```

Here's the service i use to push the image from `home assistant`:
```
service: openhasp.push_image
data:
  obj: p1b1
  image: https://YOUR_HA_ADDRESS/local/images/background.png
target:
  entity_id: openhasp.crowpanel
```

Any suggestion?

**Comment by mrgrlscz** [comment, marked as answer]
Okay.... i found the solution by myself....
```
service: openhasp.push_image
data:
  obj: p1b1
  image: https://YOUR_HA_ADDRESS/local/images/openhasp/background_800x480.jpg
  fitscreen: 1
  width: 480
  height: 800
target:
  entity_id: openhasp.crowpanel
```
As you can see... `fitscreen: 1` was missing, AND width and height are inversed, as i'm in a landscape orientation.
