### DISCUSSION TITLE
Automation into HASP btn

### DISCUSSION THREAD

**Discussion by Emu83** [HASwitchPlate/openHASP#773] [Q&A]
Hello, 

I need to change the following code so it is activated by a hasp panel button?  Essentially it will be a sync button to sync colour with another.  It is code pulled from an automation. Help please

```yaml
alias: Light sync
trigger:
  - platform: state
    entity_id: light.source
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.source
            state: 'off'
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.dest
      - conditions:
          - condition: state
            entity_id: light.source
            state: 'on'
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.dest
            data:
              rgb_color: '{{ trigger.to_state.attributes.rgb_color }}'
              brightness: '{{ trigger.to_state.attributes.brightness }}'
```
