### DISCUSSION TITLE
Display name is not recognized.

### DISCUSSION THREAD

**Discussion by Darker8989** [HASwitchPlate/openHASP#799] [Q&A] [answered]
Hello,

This is what my configuration looks like:
```yaml
openhasp:
   plate35:
    objects:
      - obj: "p0b1"  # temperature label on all pages
        properties:
          "text": '{{ states("sensor.my_room_temperature") }}°C'
      - obj: "p1b2"  # light-switch toggle button
        properties:
          "val": '{{ 1 if states("light.my_room") == "on" else 0 }}'
          "text": '{{ "\uE6E8" if is_state("light.my_room", "on") else "\uE335" | e }}'
        event:
          "up":
            - service: homeassistant.toggle
              entity_id: "light.my_room"
      - obj: "p1b3"  # dropdown
        event:
          "changed":
            - service: persistent_notification.create
              data:
                message: I like {{ text }}
```

so the example...

However, Home Assistant's log file says:
`Invalid config for 'openhasp' at openhasp.yaml, line 2: 'plate35' is an invalid option for 'openhasp', check: openhasp->openhasp->plate35, please check the docs at https://www.openhasp.com/`

Does anyone know what I'm doing wrong? 

Thanks in advance :)
