### DISCUSSION TITLE
Child objects block clickability of parent object

### DISCUSSION THREAD

**Discussion by kdw2060** [HASwitchPlate/openHASP#822] [Q&A]
Hi,

not sure if this is a bug so posting a question here first.

I have a parent object with 2 children looking like this:

```
{"id":20,"obj":"obj","x":220,"y":100,"w":190,"h":160,"click": true,"radius":10,"bg_color":"#1abd23","border_color":"#000000","bg_grad_dir":0}
{"id":21,"obj":"img","parentid":20,"x":54,"y":18,"src":"L:/kodi.png","pivot_x":0,"pivot_y":0,"zoom":90}
{"id":22,"obj":"label","parentid":20,"x":30,"y":115,"text":"Kodi kijken","text_font":"ubuntu28"}
```

and on the Home Assistant side this action associated with he parent object:
```
- obj: "p2b20" ##Test met Kodi-knop
      event:
        "up":
          - service: switch.toggle
            target: 
              entity_id: switch.plug_tuinverlichting
            data: {}
```

Now I presume the whole p2b20 object to be clickable and execute the action, but I notice I need to tap a corner. If I tap an area where the child objects are located nothing happens. 
Already tried to add `"click":true` to the child objects but that does not help.
I could off course repeat the action for all 3 objects, but that would seem to me like adding unnecessary bloat to the code.

So is this normal behaviour? Or am I making a mistake in my code? Or is this a bug?
