### DISCUSSION TITLE
Working ButtonMatrix Example?

### DISCUSSION THREAD

**Discussion by richjgould** [HASwitchPlate/openHASP#845] [General]
Hi all,

Just wondering if anyone could share a working example of the ButtonMatrix being used as a keypad?

In my JSON I have:

```
{"page":5,"comment":"---------- Page 5 ----------"}
{"id":1,"obj":"img","src":"L:/lockpicture.png","x":0,"y":40,"w":240, "auto_size":true, "enabled":true}

{"page":6,"comment":"---------- Page 6 ----------"}
{"id":1,"obj":"btnmatrix","x":10,"y":30,"w":220,"h":250,"options":["1","2","3","\n","4","5","6","\n","7","8","9","\n","*","0",".","\n","ENTER","\n"],"toggle":false,"one_check":true}
```

and the corrsponding yaml is:
```

    - obj: "p5b1"
      event:
        "hold":
          - service: openhasp.change_page
            data:
              page: 6
            target:
              entity_id: openhasp.kitchenplate

    - obj: "p6b1"
      event:
        "hold":
          - service: openhasp.change_page
            data:
              page: 1
            target:
              entity_id: openhasp.kitchenplate

```

Both pages render correctly. 
Pressing and holding the lock image takes me to page 6 correctly, but pressing any button (or anywhere) on the button matrix has no effect at all.

Ideally I'd like some guidence to using btnmatrix as a keypad to 'unlock' but at the moment I'd just be happy for any action to occur!

Any thoughts as to where I'm going wrong?

Using an L8 and the HA integration.

thanks all
