### ISSUE TITLE
Expose the display resolution / orientation values easily via device attributes

### ISSUE THREAD

**Issue by kquinsland** [HASwitchPlate/openHASP#278]
**Is your feature request related to a problem? Please describe.**

I want to use a simple layout for multiple classes of device. Each device type has a different screen resolution.
I want to define the UI elements via a normal `jsonl` file and then I want to set the X/Y cords of each widget at runtime via MQTT.

E.G.: I want three text labels to float equidistant between each other on the same line. Assuming I know the length of each label, all I need to know is what the width of the screen is to calculate where each one should go.

**Describe the solution you'd like**

If the device can send the display resolution and orientation back to the HA integration then it should be possible to do something like this:

```yaml
plate01:
  objects:
    - obj: "p0b1"
      properties:
        "text": "{{ states('sensor.foo_bar') }}"
        # Allocate 85 pixels for the text
        # We want to be centered in the left third column, check orientation then split in 3, sub 1/2 of length
        "x": >-
            {% if states.openhasp.plate01.orientation in [0,1] %}
              {{states.openhasp.plate01.xres}}3/-(85/2)
            {% else %}
              {{states.openhasp.plate01.yres}}3/-(85/2)
```

**Describe alternatives you've considered**

I considered writing my own script around jinja2 or similar to generate the yaml and or `jsonl` documents that I would use 

**Additional context**

I am trying to get a few "universal" widgets on all screens for a few different openHASP devices.
heading along the top of the screen for time and other short things
tab navigation along the bottom of each screen

The whole idea is that I can compose a few 'generic' `jsonl`file that sets the 'universal' elements to page0 and then i'll add the application specific widgets to  page 1..11.

So for the three text labels (using time, temp, humidity as examples) I would do something like this
```json
{
    "page": 0,
    "comment": "Default to page0 as the header and page/layout. x.y to be set dynamically"
}
{
    "id": 1,
    "obj": "label",
    "h": 30,
    "text": "00:00",
    "align": 0,
    "bg_color": "#2C3E50"
}
{
    "id": 2,
    "obj": "label",
    "h": 30,
    "text": "00.0°C",
    "align": 2,
    "bg_color": "#2C3E50"
}
{
    "id": 3,
    "obj": "label",
    "h": 30,
    "text": "00.0%",
    "align": 2,
    "bg_color": "#2C3E50"
}

```

And then when the device phones home, Home Assistant is then aware that it has a resolution of `320x480` but is rotated 90d so now we have 480 pixels to work with in the X direction. Assuming we want 3 pixels padding on either side, we have 474 px. Each label should be at most 158px wide.

If the display is rotated then HA can calculate the new label dimensions; increase the buffer slightly and  312/3 gives us about 100 px for each column...

... etc.

----

I don't want to maintain a library of which screens are deployed where and what the resolution is. I want the computer to figure out what the resolution is and then place the widgets at the appropriate location.
