### ISSUE TITLE
Need help with push_image

### ISSUE THREAD

**Issue by bwente** [HASwitchPlate/openHASP#473]
I am getting the following error trying to troubleshoot the problem. I think I have everything correct.

**Failed to call service openhasp.push_image. Unknown error**

```
service: openhasp.push_image
data:
  obj: p1b26
  width: 200
  height: 200
  image: https://people.sc.fsu.edu/~jburkardt/data/jpg/lena.jpg
target:
  entity_id: openhasp.wt32

```

```
{"page":1,"id":25,"obj":"obj","x":3,"y":48,"w":200,"h":200,"radius":6,"clip_corner":1,"hidden":1}
{"page":1,"id":26,"obj":"img","x":0,"y":0,"w":200,"h":200,"parentid":25,"src":"","auto_size":1}
```

<img width="399" alt="image" src="https://user-images.githubusercontent.com/371964/233877007-0a7ab808-20ac-4416-a8a2-42db1e5c0214.png">
